# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    config.vm.define "puppetserver" do |puppetserver|

        puppetserver.vm.box = "centos-7-1-x64-puppetmaster-google"
        puppetserver.vm.hostname = "puppet"

        puppetserver.vm.provider :google do |google, override|
            google.google_project_id = "audry-666"
            google.google_client_email = "account-1@audry-666.iam.gserviceaccount.com"
            google.google_json_key_location = "../packer/centos-7.1-base/google_cloud.json"
            google.name = "puppetserver"
            override.ssh.username = "vagrant"
            override.ssh.private_key_path = "~/.ssh/google"
        end
    end

    config.vm.define "nexus" do |nexus|
        nexus.vm.box = "centos-7-1-x64-google"
        nexus.vm.hostname = "nexus"

        nexus.vm.provider :google do |google, override|
            google.google_project_id = "audry-666"
            google.google_client_email = "account-1@audry-666.iam.gserviceaccount.com"
            google.google_json_key_location = "../packer/centos-7.1-base/google_cloud.json"
            google.name = "nexus"
            override.ssh.username = "vagrant"
            override.ssh.private_key_path = "~/.ssh/google"
        end
    end

    config.vm.define "gitlab" do |gitlab|
        gitlab.vm.box = "centos-7-1-x64-google"
        gitlab.vm.hostname = "nexus"

        gitlab.vm.provider :google do |google, override|
            google.google_project_id = "audry-666"
            google.google_client_email = "account-1@audry-666.iam.gserviceaccount.com"
            google.google_json_key_location = "../packer/centos-7.1-base/google_cloud.json"
            google.name = "gitlab"
            override.ssh.username = "vagrant"
            override.ssh.private_key_path = "~/.ssh/google"
        end
    end
end
